/*
 * data.js — 所有可編輯內容都集中在這支檔案
 * 改版面/功能不用碰這支檔案，改內容也不用碰其他檔案。
 *
 * 標示 [待補] 的地方，等正式資料出來（票價、歌單、口號時間軸）
 * 直接覆蓋掉對應欄位即可，畫面會自動更新。
 */

const TOUR_INFO = {
  group: "BIGBANG",
  heroKicker: "2026-2027 WORLD TOUR",
  tourName: 'BIGBANG 2026-2027 WORLD TOUR',
  tourSubtitle: '“XX : COSMOS”',
  presentedBy: "PRESENTED BY YG ENTERTAINMENT",

  showCountdown: false, // 先隱藏倒數計時，之後要顯示改成 true 即可
  showInfoSections: false, // 先隱藏「演出資訊／公告／座位圖／交通／應援禮儀／會員企劃」整組手風琴，資料還沒定案
  showOfficialSiteLink: false, // 先隱藏「官方網站」按鈕

  // 場次介紹（accordion 裡的「演出資訊」「交通方式」用，目前 accordion 是關閉的）
  // 這是世界巡演多場次，這裡先放通用文字；個別場次細節請看 TOUR_STOPS。
  venue: "詳見下方場次列表",
  venueAddress: "各場次場館不同，請依下方列表查詢",
  entryRule: "[待補，例：全場實名制 / 票券綁定，依各場次售票平台公告為準]",
  ticketPrices: [],
  ticketVendor: "[各場次售票平台待補]",
  ticketUrl: "",
  officialSiteUrl: "https://www.ygfamily.com/",
  seatMapImage: "",
  seatMapNote: "座位配置圖尚未提供，請將圖片放入 images/ 資料夾並在 data.js 的 seatMapImage 填入路徑。",
  transport: {
    mrt: ["[待補，例：搭乘 XX 線至 OO 站，OO 號出口出站即達]"],
    bus: ["[待補，公車站名與路線]"],
    driving: [
      "活動日周邊車流與停車需求高，建議不要把開車作為首選。",
      "若需開車，請先查看場館官方停車與交通公告；場館車位有限，停車不等於保證入場。",
      "散場時請依工作人員與交通管制指示離場，避免在場館周邊久候。",
    ],
  },

  // 會員／專屬企劃（例如 V.I.P 會員特典、場館限定周邊等），非必填
  membership: {
    name: "[會員企劃名稱待補，例：V.I.P MEMBERSHIP]",
    perkTitle: "[場館限定特典名稱待補]",
    description: "[待補：特典內容、對象、領取方式]",
    officialUrl: "",
  },

  // 應援禮儀文案是通用內容，先寫好可以直接用，之後想改語氣再調整就好
  etiquette: {
    intro: "不知道應援口號也沒關係。應援不是義務。這份指南整理的是「知道後會更有趣的事」，不是必須背熟的作業。安靜站著欣賞也很棒。",
    firstTime: [
      "不用全部跟著做。只要在熟悉的歌曲、熟悉的段落一起應援，就能玩得很開心。",
      "不會韓文也沒關係，很多應援口號是重複的音節或英文詞，記住發音就可以跟上。",
      "本指南的動作全部都是徒手完成，不需要另外準備應援物品。",
      "晚一拍跟著周圍的人做也完全不奇怪。",
      "場館內網路訊號可能不穩。請在家先開啟一次這個頁面，歌詞會儲存在手機裡，沒有網路也能查看。",
    ],
    together: [
      "禁止拍攝、錄音、錄影。若有允許拍攝的段落，現場會另行通知。",
      "演出中請調低手機螢幕亮度。昏暗觀眾席中的亮螢幕，後方觀眾會看得非常清楚。",
      "請避免使用手機閃光燈。舞台演出連燈光完全熄滅的瞬間都經過設計，觀眾席的一道光可能破壞那個畫面。若有全場一起舉燈的安排，演出中會另行通知。",
      "安靜歌曲、原聲樂段請克制口號與歡呼，很多人是來聽歌的。",
      "把手大幅揮過頭頂時，請留意左右與後方觀眾的視線。",
      "演出中的交談與歌曲解說，請留到曲目結束後再分享。",
      "高帽子、蓬鬆髮型可能遮擋後方觀眾視線。",
      "在人潮密集的空間裡，氣味強烈的香水可能讓他人感到不適。",
    ],
    standing: [
      "不要往前推。後方推擠的力量會直接累積到前排。",
      "大包包請放進行李寄放處，放在腳邊可能導致跌倒。",
      "如果周圍有人跌倒，請不要推擠，停下來扶起對方。",
      "入場前先喝水、先上洗手間，因為要站立數小時。",
      "若呼吸急促或頭暈，請不要勉強，告知附近的工作人員。",
    ],
    disclaimer: "本指南由粉絲製作。拍攝、攜入、再次入場等官方規定，以售票平台、場館公告與演出當天現場指示為準。",
  },

  version: "v0.2.0-skeleton",
  githubRepoUrl: "", // [待補] 之後 push 上 GitHub 後填入
  feedbackUrl: "",
  forkFromUrl: "",
};

/*
 * TOUR_STOPS — 全巡演場次清單（依官方主視覺海報建立，2026-09-21 版本）。
 * 首頁只會顯示「還沒過期」的場次（用 dateEnd 判斷，過了那天自動從清單消失），
 * 不需要手動刪除已經辦完的場次。
 *
 * 欄位說明：
 *   dateLabel  畫面上顯示的日期文字
 *   dateEnd    這場次最後一天，格式 "YYYY-MM-DD"，用來判斷是否已經過期（過期會自動隱藏）
 *   showAdded  是否顯示「SHOW ADDED」加場標籤（跟海報上一致）
 */
const TOUR_STOPS = [
  { id: "goyang", city: "GOYANG", cityZh: "高陽", venue: "GOYANG STADIUM", dateLabel: "08.21 FRI - 23.SUN", dateEnd: "2026-08-23", showAdded: false },
  { id: "oakland", city: "OAKLAND", cityZh: "奧克蘭", venue: "OAKLAND-ALAMEDA COUNTY COLISEUM", dateLabel: "09.04 FRI - 05.SAT", dateEnd: "2026-09-05", showAdded: true },
  { id: "east-rutherford", city: "EAST RUTHERFORD", cityZh: "東拉塞福", venue: "METLIFE STADIUM", dateLabel: "09.11 FRI", dateEnd: "2026-09-11", showAdded: false },
  { id: "paris", city: "PARIS", cityZh: "巴黎", venue: "STADE DE FRANCE", dateLabel: "09.19 SAT", dateEnd: "2026-09-19", showAdded: false },
  { id: "london", city: "LONDON", cityZh: "倫敦", venue: "TOTTENHAM HOTSPUR STADIUM", dateLabel: "09.26 SAT", dateEnd: "2026-09-26", showAdded: false },
  { id: "taipei", city: "TAIPEI", cityZh: "台北", venue: "TAIPEI DOME", dateLabel: "10.09 FRI - 11.SUN", dateEnd: "2026-10-11", showAdded: true },
  { id: "singapore", city: "SINGAPORE", cityZh: "新加坡", venue: "SINGAPORE NATIONAL STADIUM", dateLabel: "10.17 SAT", dateEnd: "2026-10-17", showAdded: false },
  { id: "hanoi", city: "HANOI", cityZh: "河內", venue: "MY DINH NATIONAL STADIUM", dateLabel: "10.24 SAT - 25.SUN", dateEnd: "2026-10-25", showAdded: false },
  { id: "sydney", city: "SYDNEY", cityZh: "雪梨", venue: "ACCOR STADIUM", dateLabel: "10.31 SAT", dateEnd: "2026-10-31", showAdded: false },
  { id: "bangkok", city: "BANGKOK", cityZh: "曼谷", venue: "RAJAMANGALA NATIONAL STADIUM", dateLabel: "11.07 SAT", dateEnd: "2026-11-07", showAdded: false },
  { id: "hong-kong", city: "HONG KONG", cityZh: "香港", venue: "KAI TAK STADIUM", dateLabel: "11.13 FRI - 15.SUN", dateEnd: "2026-11-15", showAdded: false },
  { id: "osaka", city: "OSAKA", cityZh: "大阪", venue: "KYOCERA DOME OSAKA", dateLabel: "11.27 FRI - 29.SUN", dateEnd: "2026-11-29", showAdded: false },
  { id: "nagoya", city: "NAGOYA", cityZh: "名古屋", venue: "VANTELIN DOME NAGOYA", dateLabel: "12.05 SAT - 06.SUN", dateEnd: "2026-12-06", showAdded: false },
  { id: "tokyo", city: "TOKYO", cityZh: "東京", venue: "TOKYO DOME", dateLabel: "12.13 SUN - 15.TUE", dateEnd: "2026-12-15", showAdded: false },
  { id: "fukuoka", city: "FUKUOKA", cityZh: "福岡", venue: "MIZUHO PAYPAY DOME FUKUOKA", dateLabel: "12.26 SAT - 27.SUN", dateEnd: "2026-12-27", showAdded: false },
  { id: "kuala-lumpur", city: "KUALA LUMPUR", cityZh: "吉隆坡", venue: "TM STADIUM NASIONAL", dateLabel: "01.09 SAT", dateEnd: "2027-01-09", showAdded: false },
  { id: "jakarta", city: "JAKARTA", cityZh: "雅加達", venue: "JAKARTA INTERNATIONAL STADIUM", dateLabel: "01.16 SAT", dateEnd: "2027-01-16", showAdded: false },
  { id: "manila", city: "MANILA", cityZh: "馬尼拉", venue: "SMDC FESTIVAL GROUNDS", dateLabel: "02.20 SAT", dateEnd: "2027-02-20", showAdded: true },
  { id: "kaohsiung", city: "KAOHSIUNG", cityZh: "高雄", venue: "KAOHSIUNG NATIONAL STADIUM", dateLabel: "02.27 SAT - 28.SUN", dateEnd: "2027-02-28", showAdded: false },
];

/*
 * 應援標記類型，對應原本 VAUNDY 指南的「大合唱／拍手／揮手／跳躍／轉臂」。
 * 韓國團體場合常見用語可以改成：떼창(大合唱)／박수(拍手)／손 흔들기(揮手) 等，
 * 這裡先沿用中文標籤方便閱讀，key 不要改（程式邏輯用 key 判斷），label 可以改。
 */
const CHANT_TYPES = {
  call:  { key: "call",  label: "大合唱" },
  cheer: { key: "cheer", label: "應援詞" }, // 喊出來的口號，跟跟著唱的「大合唱」不同
  clap:  { key: "clap",  label: "拍手" },
};

/*
 * SONGS：每首歌一筆。lyrics 是逐句歌詞，time 是「距離影片開頭幾秒」，
 * 用來做點擊跳轉與自動高亮。這裡先放 5 首示範曲目、內容全部是占位文字，
 * 不是真實歌詞——正式歌單/口號/時間軸確定後，整批覆蓋這個陣列即可。
 *
 * 欄位說明：
 *   id            唯一代碼，網址會用到（例：#/song/demo-01），建議用羅馬拼音曲名
 *   title         中文/慣用曲名
 *   titleOriginal 原文曲名（韓文）
 *   youtubeId     YouTube 影片 ID（網址 v= 後面那串），留空則畫面顯示「尚未設定影片」
 *   chantTypes    這首歌用到哪些應援類型（給歌曲清單上的標記用）
 *   categories    自訂分類標籤，陣列，名稱完全自訂（例：["安可曲","抒情"]），
 *                 應援指南頁可以用這個多選篩選；不需要分類就留空陣列 []
 *   lyrics[]:
 *     time        秒數（數字）
 *     original    原文歌詞（韓文）
 *     romaji      羅馬拼音（給不會韓文的歌迷跟著唱）
 *     zh          中文翻譯
 *     chant       這句對應的應援類型 key（null 表示這句沒有特別應援動作）
 */
const SONGS = [
  {
    id: "fantastic-baby",
    order: 1,
    title: "FANTASTIC BABY",
    titleOriginal: "",
    youtubeId: "IOXR43u_cqw",
    chantTypes: ["call", "cheer"],
    categories: ["舞曲"],
    lyrics: [
      { time: 3, original: "여기 붙어라", romaji: "yeogi buteora", zh: "靠過來這裡吧", kongEr: "211*111*", chant: null },
      { time: 7, original: "모두 모여라", romaji: "modu moyeora", zh: "全都聚集過來吧", kongEr: "", chant: null },
      { time: 11, original: "WE GON' PARTY LIKE RIRIRILALALA", romaji: "", zh: "WE GON' PARTY LIKE RIRIRILALALA", kongEr: "", chant: null },
      { time: 13.2, original: "맘을 열어라", romaji: "mameul yeoleora", zh: "敞開你的心", kongEr: "", chant: null },
      { time: 17.2, original: "머릴 비워라", romaji: "meoril biwora", zh: "清除雜念 放空你的腦", kongEr: "", chant: null },
      { time: 21.2, original: "불을 지펴라 리리리라라라", romaji: "bureul jipyeora ririllallalla", zh: "點燃心中的火焰 RIRIRILALALA", kongEr: "", chant: null },
      { time: 25.2, original: "정답은 묻지 말고 그대로 받아들여 느낌대로 가", romaji: "jeongdabeun mutji malgo geudaero badadeulyeo neukkimdaelo ga", zh: "不要問答案 就只要接受 跟著感覺走吧", kongEr: "", chant: null },
      { time: 29.2, original: "ALRIGHT", romaji: "", zh: "ALRIGHT", kongEr: "", chant: null },
      { time: 31.4, original: "하늘을 마주하고 두 손을 다 위로", romaji: "haneureul majuhago du soneul da wilo", zh: "對著天空 高舉起你的雙手", kongEr: "", chant: null },
      { time: 35.4, original: "저 위로 날뛰고 싶어 OH", romaji: "jeo wilo nalttwigo sipeo OH", zh: "想朝向那高處瘋狂亂跳 OH", kongEr: "", chant: null },
      { time: 39.4, original: "NANANANANA NANANANANA", romaji: "", zh: "NANANANANA NANANANANA", kongEr: "", chant: "call" },
      { time: 41.6, original: "WOW FANTASTIC BABY", romaji: "", zh: "WOW FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 43.8, original: "DANCE", romaji: "", zh: "DANCE", kongEr: "", chant: null },
      { time: 46, original: "I WANNA DAN DAN DAN DAN DANCE", romaji: "", zh: "I WANNA DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 48.2, original: "FANTASTIC BABY", romaji: "", zh: "FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 50.4, original: "DANCE", romaji: "", zh: "DANCE", kongEr: "", chant: null },
      { time: 52.6, original: "I WANNA DAN DAN DAN DAN DANCE", romaji: "", zh: "I WANNA DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 54.8, original: "WOW FANTASTIC BABY", romaji: "", zh: "WOW FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 57, original: "이 난장판에 HEY", romaji: "i nanjangpane HEY", zh: "在這場亂仗中 HEY", kongEr: "", chant: "call" },
      { time: 61, original: "끝판 왕 차례 HEY", romaji: "kkeutpan wang chalye HEY", zh: "最後 該國王登場了 HEY", kongEr: "", chant: "call" },
      { time: 65, original: "땅을 흔들고 3분으론 불충분한 RACE", romaji: "ttangeul heundeulgo 3buneuron bulchungbunhan RACE", zh: "地板在搖晃 3分鐘 不足夠的RACE", kongEr: "", chant: null },
      { time: 69, original: "WAIT 분위기는 과열 HUH", romaji: "WAIT bunwigineun gwayeol HUH", zh: "WAIT 氣氛超越沸點 HUH", kongEr: "", chant: null },
      { time: 73, original: "CATCH ME ON FIRE HUH", romaji: "", zh: "CATCH ME ON FIRE HUH", kongEr: "", chant: null },
      { time: 75.2, original: "진짜가 나타났다 NANANANANA", romaji: "jinjjaga natanatda NANANANANA", zh: "主角出現了", kongEr: "", chant: "call" },
      { time: 79.2, original: "하나부터 열까지 모든 게 다 한수위(翰數wi)", romaji: "hanabuteo yeolkkaji modeun ge da hansuwi", zh: "從一到十 全都高人一等", kongEr: "", chant: "call" },
      { time: 83.2, original: "모래 벌판 위를 미친 듯이 뛰어봐도 거뜬한 우리(翰物理)", romaji: "mole beolpan wireul michin deusi ttwieobwado geotteunhan uri", zh: "即使在廣闊沙地上瘋狂跳躍也一派輕鬆的我們", kongEr: "", chant: "call" },
      { time: 87.2, original: "하늘은 충분히(搶本魚-台語) 너무나 푸르니(噗ㄌ你)까", romaji: "haneureun chungbunhi neomuna puleunikka", zh: "因為天空是如此蔚藍", kongEr: "", chant: "call" },
      { time: 91.2, original: "아무것도 묻지 말란 말이야 느끼란 말이야 내가 누군지(努估幾)", romaji: "amugeotdo mutji mallan mariya neukkiran mariya naega nugunji", zh: "什麼都別多問 只要去感覺 讓你知道我是誰", kongEr: "", chant: "call" },
      { time: 95.2, original: "네 심장소리에 맞게 뛰기 시작해 막이 끝날 때까지 YE", romaji: "ne simjangsolie matge ttwigi sijakhae magi kkeutnal ttaekkaji YE", zh: "跟著你心臟的鼓動聲 開始跳吧 直到派對落幕為止 YE", kongEr: "", chant: null },
      { time: 99.2, original: "I CAN'T BABY DON'T' STOP THIS", romaji: "", zh: "I CAN'T BABY DON'T' STOP THIS", kongEr: "", chant: null },
      { time: 101.4, original: "오늘은 타락해 (미쳐 발악해) 가는거야", romaji: "oneureun tarakhae (michyeo baraghae) ganeungeoya", zh: "今天就來墮落 (瘋狂掙扎 放肆) 一場吧", kongEr: "", chant: null },
      { time: 105.4, original: "WOW FANTASTIC BABY", romaji: "", zh: "WOW FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 107.6, original: "DANCE", romaji: "", zh: "DANCE", kongEr: "", chant: null },
      { time: 109.8, original: "I WANNA DAN DAN DAN DAN DANCE", romaji: "", zh: "I WANNA DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 112, original: "FANTASTIC BABY", romaji: "", zh: "FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 114.2, original: "DANCE", romaji: "", zh: "DANCE", kongEr: "", chant: null },
      { time: 116.4, original: "I WANNA DAN DAN DAN DAN DANCE", romaji: "", zh: "I WANNA DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 118.6, original: "WOW FANTASTIC BABY", romaji: "", zh: "WOW FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 120.8, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 123, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 125.2, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 127.4, original: "DAN DAN DAN DAN DANCE", romaji: "", zh: "DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 129.6, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 131.8, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 134, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 136.2, original: "DAN DAN DAN DAN DANCE", romaji: "", zh: "DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 138.4, original: "날 따라 잡아볼 테면 와봐 난 영원한 딴따라", romaji: "nal ttara jababol temyeon wabwa nan yeongwonhan ttanttara", zh: "想學我的話就來試看看吧 我永遠都不同凡響", kongEr: "", chant: null },
      { time: 142.4, original: "오늘 밤 금기란 내겐 없어", romaji: "oneul bam geumgiran naegen eopseo", zh: "今夜 對我來說沒有 禁忌", kongEr: "", chant: null },
      { time: 146.4, original: "MAMA JUST LET ME BE YOUR LOVER", romaji: "", zh: "MAMA JUST LET ME BE YOUR LOVER", kongEr: "", chant: null },
      { time: 148.6, original: "이 혼란 속을 넘어 NANANANANA", romaji: "i honlan sogeul neomeo NANANANANA", zh: "沉浸在這混亂之中", kongEr: "", chant: "call" },
      { time: 152.6, original: "머리끝부터 발끝까지 비쥬얼은 쇼크", romaji: "meorikkeutbuteo balkkeutkkaji bijyueoreun syokeu", zh: "從頭到腳 視覺效果都帶來SHOCK", kongEr: "", chant: null },
      { time: 156.6, original: "내 감각은 소문난 꾼 앞서가는 촉", romaji: "nae gamgageun somunnan kkun apseoganeun chok", zh: "我的品味是出了名的達人等級 總是領先超前", kongEr: "", chant: null },
      { time: 160.6, original: "남들보다는 빠른 걸음", romaji: "namdeulbodaneun ppareun georeum", zh: "比別人更快的腳步", kongEr: "", chant: null },
      { time: 164.6, original: "차원이 다른 젊음", romaji: "chawoni dareun jeolmeum", zh: "不同次元的青春", kongEr: "", chant: null },
      { time: 168.6, original: "얼음얼음얼음 HOLD UP NANANANANA", romaji: "eoreum eoreum eoreum HOLD UP NANANANANA", zh: "站住 站住 站住 HOLD UP", kongEr: "", chant: "call" },
      { time: 172.6, original: "네 심장소리에 맞게 뛰기 시작해 막이 끝날 때까지 YE", romaji: "ne simjangsolie matge ttwigi sijakhae magi kkeutnal ttaekkaji YE", zh: "跟著你心臟的鼓動聲 開始跳吧 直到派對落幕為止 YE", kongEr: "", chant: null },
      { time: 176.6, original: "I CAN'T BABY DON'T' STOP THIS", romaji: "", zh: "I CAN'T BABY DON'T' STOP THIS", kongEr: "", chant: null },
      { time: 178.8, original: "오늘은 타락해 (미쳐 발악해) 가는거야", romaji: "oneureun tarakhae (michyeo baraghae) ganeungeoya", zh: "今天就來墮落 (瘋狂掙扎 放肆) 一場吧", kongEr: "", chant: null },
      { time: 182.8, original: "WOW FANTASTIC BABY", romaji: "", zh: "WOW FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 185, original: "DANCE", romaji: "", zh: "DANCE", kongEr: "", chant: null },
      { time: 187.2, original: "I WANNA DAN DAN DAN DAN DANCE", romaji: "", zh: "I WANNA DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 189.4, original: "FANTASTIC BABY", romaji: "", zh: "FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 191.6, original: "DANCE", romaji: "", zh: "DANCE", kongEr: "", chant: null },
      { time: 193.8, original: "I WANNA DAN DAN DAN DAN DANCE", romaji: "", zh: "I WANNA DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 196, original: "WOW FANTASTIC BABY", romaji: "", zh: "WOW FANTASTIC BABY", kongEr: "", chant: "call" },
      { time: 198.2, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 200.4, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 202.6, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 204.8, original: "DAN DAN DAN DAN DANCE", romaji: "", zh: "DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 207, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 209.2, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 211.4, original: "BOOMSHAKALAKA BOOM", romaji: "", zh: "BOOMSHAKALAKA BOOM", kongEr: "", chant: "cheer" },
      { time: 213.6, original: "DAN DAN DAN DAN DANCE", romaji: "", zh: "DAN DAN DAN DAN DANCE", kongEr: "", chant: null },
      { time: 215.8, original: "다 같이 놀자 YE YE YE", romaji: "da gachi nolja YE YE YE", zh: "大家一起玩吧", kongEr: "", chant: "call" },
      { time: 219.1, original: "다 같이 뛰자 YE YE YE", romaji: "da gachi ttwija YE YE YE", zh: "大家一起跳吧", kongEr: "", chant: "call" },
      { time: 222.4, original: "다 같이 돌자 YE YE YE", romaji: "da gachi dolja YE YE YE", zh: "大家一起瘋吧", kongEr: "", chant: "call" },
      { time: 225.7, original: "다 같이 가자", romaji: "da gachi gaja", zh: "大家一起走吧", kongEr: "", chant: null },
      { time: 228.5, original: "WOW FANTASTIC BABY", romaji: "", zh: "WOW FANTASTIC BABY", kongEr: "", chant: "call" },
    ],
  },
  {
    id: "hands-up",
    order: 2,
    title: "HANDS UP",
    titleOriginal: "",
    youtubeId: "0o7qE6pCxI0",
    chantTypes: ["call"],
    categories: ["1st"],
    // 歌詞來源：BIGBANG空耳應援歌詞（N.YDest 空耳／翻譯：大勝鉉愛小志龍），時間點為粗估，待對照影片微調
    lyrics: [
      { time: 3.0, original: "Brand new world is comming", romaji: "", zh: "Brand new world is comming", chant: null },
      { time: 6.0, original: "We are the world", romaji: "", zh: "We are the world", chant: null },
      { time: 9.0, original: "Say hello to the world", romaji: "", zh: "Say hello to the world", chant: null },
      { time: 12.0, original: "Into my world hello to world", romaji: "", zh: "Into my world hello to world", chant: null },
      { time: 15.0, original: "The world we are the world", romaji: "", zh: "The world we are the world", chant: null },
      { time: 18.0, original: "**Hey ho Hey ho** Let me say", romaji: "", zh: "Hey ho Hey ho Let me say", chant: "call" },
      { time: 21.0, original: "**Hey ho Hey ho** One more time", romaji: "", zh: "Hey ho Hey ho One more time", chant: "call" },
      { time: 24.0, original: "**Hey ho Hey ho** Let me say", romaji: "", zh: "Hey ho Hey ho Let me say", chant: "call" },
      { time: 27.0, original: "**Hey ho Hey ho** Breathe", romaji: "", zh: "Hey ho Hey ho Breathe", chant: "call" },
      { time: 30.0, original: "Hands up high high&low", romaji: "", zh: "Hands up high high&low", chant: null },
      { time: 33.0, original: "그대와나 음악소리에 잠시 기대", romaji: "geudaewana eumaksorie jamsi gidae", zh: "你和我一起在這音樂聲中暫時等待一下", chant: null },
      { time: 36.0, original: "Hands up high high&low", romaji: "", zh: "Hands up high high&low", chant: "call" },
      { time: 39.0, original: "느낌따라 Just one step two step", romaji: "neukkimttara Just one step two step", zh: "跟著感覺", chant: null },
      { time: 42.0, original: "Hands up high Don't stop the beat", romaji: "", zh: "Hands up high Don't stop the beat", chant: null },
      { time: 45.0, original: "네 키보다 더 높이", romaji: "ne kiboda deo nopi", zh: "比你的身高再更高一點", chant: null },
      { time: 48.0, original: "Hands up high 링링링링 정신없이 몸을 비틀어놔", romaji: "Hands up high ringringringring jeongsineopsi momeul biteureonwa", zh: "瘋狂的扭動身體吧", chant: null },
      { time: 51.0, original: "말리지마 We don't care", romaji: "mallijima We don't care", zh: "別壓抑別阻擋", chant: null },
      { time: 54.0, original: "Let's work it Let's work it", romaji: "", zh: "Let's work it Let's work it", chant: null },
      { time: 57.0, original: "Let's work it now", romaji: "", zh: "Let's work it now", chant: null },
      { time: 60.0, original: "자 그려봐 네가 원하는 꿈을 나에게 말해봐", romaji: "ja geuryeobwa nega wonhaneun kkumeul naege malhaebwa", zh: "來 試著描繪看看 把你所渴望的夢想跟我說吧", chant: null },
      { time: 63.0, original: "언제든 데려가 줄 테니", romaji: "eonjedeun deryeoga jul teni", zh: "無論何時 我都會帶領著你", chant: null },
      { time: 66.0, original: "불러봐 너의 누군가를 위해", romaji: "bulleobwa neoui nugungareul wihae", zh: "大喊吧 為了你的那個誰", chant: null },
      { time: 69.0, original: "Baby just 1,2,3 go", romaji: "", zh: "Baby just 1,2,3 go", chant: null },
      { time: 72.0, original: "Hands up high high & low", romaji: "", zh: "Hands up high high & low", chant: null },
      { time: 75.0, original: "그대와나 음악소리에 잠시 기대", romaji: "geudaewana eumaksorie jamsi gidae", zh: "你和我一起在這音樂聲中暫時等待一下", chant: null },
      { time: 78.0, original: "Hands up high high & low", romaji: "", zh: "Hands up high high & low", chant: "call" },
      { time: 81.0, original: "느낌따라 Just one step two step", romaji: "neukkimttara Just one step two step", zh: "跟著感覺", chant: null },
      { time: 84.0, original: "Everybody plz don't stop", romaji: "", zh: "Everybody plz don't stop", chant: null },
      { time: 87.0, original: "내 목소리 들리게", romaji: "nae moksori deullige", zh: "讓你聽見我的聲音", chant: null },
      { time: 90.0, original: "아침해가 밝아와도", romaji: "achimhaega balgawado", zh: "即使早晨來臨 朝陽照射", chant: null },
      { time: 93.0, original: "Just we belong together", romaji: "", zh: "Just we belong together", chant: null },
      { time: 96.0, original: "Everybody plz don't stop", romaji: "", zh: "Everybody plz don't stop", chant: null },
      { time: 99.0, original: "You got me goin crazy", romaji: "", zh: "You got me goin crazy", chant: null },
      { time: 102.0, original: "우릴따라 Just one step two step", romaji: "urittara Just one step two step", zh: "跟著我們", chant: null },
      { time: 105.0, original: "I said a louder", romaji: "", zh: "I said a louder", chant: null },
      { time: 108.0, original: "목이 터져라 질러봐 이곳은 Rush hour", romaji: "mogi teojyeora jilleobwa igoseun Rush hour", zh: "像要撕裂嗓子般的高聲吶喊吧 這個地方", chant: null },
      { time: 111.0, original: "혼잡한 세상 바삐 돌아가는 시계추 boom boom pow", romaji: "honjabhan sesang bappi doraganeun sigyechu boom boom pow", zh: "混亂的世界 匆忙擺盪著的鐘擺", chant: null },
      { time: 114.0, original: "What about you boom boom down", romaji: "", zh: "What about you boom boom down", chant: null },
      { time: 117.0, original: "Let's work it", romaji: "", zh: "Let's work it", chant: null },
      { time: 120.0, original: "Let's work it", romaji: "", zh: "Let's work it", chant: null },
      { time: 123.0, original: "Let's work it now", romaji: "", zh: "Let's work it now", chant: null },
      { time: 126.0, original: "자 그려봐 네가 바라는 꿈을 나에게 말해봐", romaji: "ja geuryeobwa nega baraneun kkumeul naege malhaebwa", zh: "來 試著描繪看看 把你所渴望的夢想跟我說吧", chant: null },
      { time: 129.0, original: "어디든 데려가 줄 테니", romaji: "eodideun deryeoga jul teni", zh: "無論何地 我都會帶領著你", chant: null },
      { time: 132.0, original: "불러봐 너의 누군가를 향해", romaji: "bulleobwa neoui nugungareul hyanghae", zh: "大喊吧 向著你的那個誰", chant: null },
      { time: 135.0, original: "Baby just 1,2,3 go", romaji: "", zh: "Baby just 1,2,3 go", chant: null },
      { time: 138.0, original: "Hands up high high&low", romaji: "", zh: "Hands up high high&low", chant: null },
      { time: 141.0, original: "그대와나 음악소리에 잠시 기대", romaji: "geudaewana eumaksorie jamsi gidae", zh: "你和我一起在這音樂聲中暫時等待一下", chant: null },
      { time: 144.0, original: "Hands up high high&low", romaji: "", zh: "Hands up high high&low", chant: "call" },
      { time: 147.0, original: "느낌따라 Just one step two step", romaji: "neukkimttara Just one step two step", zh: "跟著感覺", chant: null },
      { time: 150.0, original: "（一起舉起手手）", romaji: "", zh: "（一起舉起手手）", chant: "call" },
      { time: 153.0, original: "Now put your hands up", romaji: "", zh: "Now put your hands up", chant: null },
      { time: 156.0, original: "Now put your hands up", romaji: "", zh: "Now put your hands up", chant: null },
      { time: 159.0, original: "Now put your hands up", romaji: "", zh: "Now put your hands up", chant: null },
      { time: 162.0, original: "Now everybody put your hands up", romaji: "", zh: "Now everybody put your hands up", chant: null },
      { time: 165.0, original: "**Hey ho Hey ho** let me say", romaji: "", zh: "Hey ho Hey ho let me say", chant: "call" },
      { time: 168.0, original: "**Hey ho Hey ho** one more time", romaji: "", zh: "Hey ho Hey ho one more time", chant: "call" },
      { time: 171.0, original: "**Hey ho Hey ho** let me hear you say", romaji: "", zh: "Hey ho Hey ho let me hear you say", chant: "call" },
      { time: 174.0, original: "**Hey ho Hey ho** breathe", romaji: "", zh: "Hey ho Hey ho breathe", chant: "call" },
      { time: 177.0, original: "Hands up high high & low", romaji: "", zh: "Hands up high high & low", chant: null },
      { time: 180.0, original: "그대와나 음악소리에 잠시 기대", romaji: "geudaewana eumaksorie jamsi gidae", zh: "你和我一起在這音樂聲中暫時等待一下", chant: null },
      { time: 183.0, original: "Hands up high high & low", romaji: "", zh: "Hands up high high & low", chant: "call" },
      { time: 186.0, original: "느낌따라 Just one step two step", romaji: "neukkimttara Just one step two step", zh: "跟著感覺", chant: null },
      { time: 189.0, original: "Hands up high high & low", romaji: "", zh: "Hands up high high & low", chant: null },
      { time: 192.0, original: "그대와나 음악소리에 잠시 기대", romaji: "geudaewana eumaksorie jamsi gidae", zh: "你和我一起在這音樂聲中暫時等待一下", chant: null },
      { time: 195.0, original: "Hands up high high & low", romaji: "", zh: "Hands up high high & low", chant: null },
      { time: 198.0, original: "느낌따라 Just one step two step", romaji: "neukkimttara Just one step two step", zh: "跟著感覺", chant: null },
    ],
  },
  {
    id: "tonight",
    order: 3,
    title: "TONIGHT",
    titleOriginal: "",
    youtubeId: "xWUGRnBb45Y",
    chantTypes: ["call", "cheer"],
    categories: ["1st"],
    // 歌詞來源：BIGBANG空耳應援歌詞（N.YDest 空耳／翻譯：大勝鉉愛小志龍），時間點為粗估，待對照影片微調
    lyrics: [
      { time: 3.0, original: "Tonight such a beautiful night", romaji: "", zh: "Tonight such a beautiful night", chant: null },
      { time: 6.0, original: "Sing with me now 2011 follow me", romaji: "", zh: "Sing with me now 2011 follow me", chant: null },
      { time: 9.0, original: "BIGBANG BIGBANG", romaji: "", zh: "BIGBANG BIGBANG", chant: "call" },
      { time: 12.0, original: "We're back again one more time say", romaji: "", zh: "We're back again one more time say", chant: null },
      { time: 15.0, original: "No way No way", romaji: "", zh: "No way No way", chant: "call" },
      { time: 18.0, original: "너무 쉽게 또 남이 돼", romaji: "neomu swipge tto nami dwae", zh: "如此簡單的又成為陌生人了", chant: null },
      { time: 21.0, original: "BIGBANG BIGBANG", romaji: "", zh: "BIGBANG BIGBANG", chant: "call" },
      { time: 24.0, original: "Don't stop", romaji: "", zh: "Don't stop", chant: null },
      { time: 27.0, original: "Let's play **ok ok** go go go", romaji: "", zh: "Let's play ok ok go go go", chant: "call" },
      { time: 30.0, original: "나 미칠 것 같애", romaji: "na michil geot gatae", zh: "我好像瘋了", chant: null },
      { time: 33.0, original: "아마 지친 것 같애", romaji: "ama jichin geot gatae", zh: "大概是累了吧", chant: null },
      { time: 36.0, original: "아냐 질린 것 같애", romaji: "anya jillin geot gatae", zh: "不對 應該是厭倦了", chant: null },
      { time: 39.0, original: "벌써 따분해 시시해", romaji: "beolsseo ttabunhae sisihae", zh: "很快就覺得煩覺得沒意思", chant: null },
      { time: 42.0, original: "한 여자로는 만족 못 하는 bad boy but I'm nice", romaji: "han yeojaroneun manjok mot haneun bad boy but I'm nice", zh: "我是無法只滿足於一個女人的bad boy but I'm nice", chant: null },
      { time: 45.0, original: "안 넘어가고는 못 배길걸", romaji: "an neomeogagoneun mot baegilgeol", zh: "無法忍受有人不淪陷", chant: null },
      { time: 48.0, original: "Let me blow ya mind", romaji: "", zh: "Let me blow ya mind", chant: null },
      { time: 51.0, original: "언제부터였는지", romaji: "eonjebuteoyeonneunji", zh: "是從什麼時候開始的", chant: null },
      { time: 54.0, original: "감흥이 없어진 우리", romaji: "gamheungi eopseojin uri", zh: "對彼此沒了興趣的我們", chant: null },
      { time: 57.0, original: "이젠 마치 진 빠진", romaji: "ijen machi jin ppajin", zh: "現在大概已經耗盡精力", chant: null },
      { time: 60.0, original: "김 빠진 콜라같지", romaji: "gim ppajin kollagatji", zh: "就好像沒氣的可樂", chant: null },
      { time: 63.0, original: "무감각해진 첫 느낌", romaji: "mugamgakhaejin cheot neukkim", zh: "毫無感覺的第一印象", chant: null },
      { time: 66.0, original: "서로를 향한 곁눈질", romaji: "seororeul hyanghan gyeotnunjil", zh: "望向彼此的斜眼目光", chant: null },
      { time: 69.0, original: "그깟 사랑에 난 목매지 않아", romaji: "geugkkat sarange nan mokmaeji ana", zh: "我才不會投身於這種愛情之中", chant: null },
      { time: 72.0, original: "Don't wanna try no more", romaji: "", zh: "Don't wanna try no more", chant: null },
      { time: 75.0, original: "너를 찾아서 **Oh A oh**", romaji: "neoreul chajaseo Oh A oh", zh: "為了找尋你", chant: "call" },
      { time: 78.0, original: "날 비춰주는 저 달빛아래로", romaji: "nal bichwojuneun jeo dalbicharaero", zh: "走向那照耀著我的月光之下", chant: null },
      { time: 81.0, original: "그댈 찾아서 **Oh A oh oh oh**", romaji: "geudael chajaseo Oh A oh oh oh", zh: "為了找尋親愛的你", chant: "call" },
      { time: 84.0, original: "끝이 어딘지 모르겠지만 Hey", romaji: "kkeuchi eodinji moreugetjiman Hey", zh: "雖然不知道盡頭在哪", chant: null },
      { time: 87.0, original: "Tonight Tonight Tonight Tonight", romaji: "", zh: "Tonight Tonight Tonight Tonight", chant: null },
      { time: 90.0, original: "아직 난 사랑을 몰라", romaji: "ajik nan sarangeul molla", zh: "我現在還不懂愛情", chant: null },
      { time: 93.0, original: "또 홀로 가여운 이 밤 **사랑해**", romaji: "tto hollo gayeoun i bam saranghae", zh: "又是獨自一人淒涼的夜晚", kongEr: "撒朗嘿", chant: "cheer" },
      { time: 96.0, original: "상처 난 이별이 무서워", romaji: "sangcheo nan ibyeori museowo", zh: "我害怕讓人受傷的離別", chant: null },
      { time: 99.0, original: "So what So what", romaji: "", zh: "So what So what", chant: "call" },
      { time: 102.0, original: "널 처음 만난 순간이 그리워", romaji: "neol cheoeum mannan sungani geuriwo", zh: "想念初次見到你的那個瞬間", chant: null },
      { time: 105.0, original: "No more No more", romaji: "", zh: "No more No more", chant: "call" },
      { time: 108.0, original: "그저 아픔에 서툰 걸", romaji: "geujeo apeume seotun geol", zh: "我只是不習慣傷痛", chant: null },
      { time: 111.0, original: "난 피하고 싶은 걸", romaji: "nan pihago sipeun geol", zh: "我想要逃避", chant: null },
      { time: 114.0, original: "But You know that I love you girl girl girl", romaji: "", zh: "But You know that I love you girl girl girl", chant: null },
      { time: 117.0, original: "질질끄는 성격 Say no", romaji: "jiljilkkeuneun seonggyeok Say no", zh: "拖泥帶水的個性 Say no", chant: null },
      { time: 120.0, original: "차가운 입술로 널 얼어 붙게 하는 나나나", romaji: "chagaun ipsullo neol eoreo butge haneun nanana", zh: "用冰冷的唇 凍結你的我 我 我", chant: null },
      { time: 123.0, original: "Take ma soul take ma heart back", romaji: "", zh: "Take ma soul take ma heart back", chant: null },
      { time: 126.0, original: "새로운 설레임 Get that", romaji: "saeroun seolleim Get that", zh: "全新的悸動 Get that", chant: null },
      { time: 129.0, original: "사랑은 내게는 어울리지 않아", romaji: "sarangeun naegeneun eoullji ana", zh: "愛情並不適合我", chant: null },
      { time: 132.0, original: "Don't think too much it's simple", romaji: "", zh: "Don't think too much it's simple", chant: null },
      { time: 135.0, original: "너를 찾아서 **Oh A oh**", romaji: "neoreul chajaseo Oh A oh", zh: "為了找尋你", chant: "call" },
      { time: 138.0, original: "날 비춰주는 저 달빛아래로", romaji: "nal bichwojuneun jeo dalbicharaero", zh: "走向那照耀著我的月光之下", chant: null },
      { time: 141.0, original: "그댈 찾아서 **Oh A oh oh oh**", romaji: "geudael chajaseo Oh A oh oh oh", zh: "為了找尋親愛的你", chant: "call" },
      { time: 144.0, original: "끝이 어딘지는 모르겠지만 Hey", romaji: "kkeuchi eodinjineun moreugetjiman Hey", zh: "雖然不知道盡頭在哪", chant: null },
      { time: 147.0, original: "Tonight Tonight Tonight Tonight", romaji: "", zh: "Tonight Tonight Tonight Tonight", chant: null },
      { time: 150.0, original: "아직 난 사랑을 몰라", romaji: "ajik nan sarangeul molla", zh: "我現在還不懂愛情", chant: null },
      { time: 153.0, original: "또 홀로 가여운 이 밤 **사랑해**", romaji: "tto hollo gayeoun i bam saranghae", zh: "又是獨自一人淒涼的夜晚", kongEr: "撒朗嘿", chant: "cheer" },
      { time: 156.0, original: "+ BIGBANG BIGBANG", romaji: "", zh: "BIGBANG BIGBANG", chant: null },
      { time: 159.0, original: "+ We're back again one more time say", romaji: "", zh: "We're back again one more time say", chant: null },
      { time: 162.0, original: "**+ No way No way**", romaji: "", zh: "No way No way", chant: "call" },
      { time: 165.0, original: "+ 너무 쉽게 또 남이 돼", romaji: "neomu swipge tto nami dwae", zh: "如此簡單的又成為陌生人了", chant: null },
      { time: 168.0, original: "**+ BIGBANG BIGBANG**", romaji: "", zh: "BIGBANG BIGBANG", chant: "call" },
      { time: 171.0, original: "+ Don't stop", romaji: "", zh: "Don't stop", chant: null },
      { time: 174.0, original: "+ Let's play **ok ok** go go go", romaji: "", zh: "Let's play ok ok go go go", chant: "call" },
      { time: 177.0, original: "안녕이란 말의 슬픈 의미", romaji: "annyeongiran marui seulpeun uimi", zh: "再見 這種話裡悲傷的意義", chant: null },
      { time: 180.0, original: "어두운 그림자는 가려지고", romaji: "eoduun geurimjaneun garyeojigo", zh: "陰暗的影子被掩蓋", chant: null },
      { time: 183.0, original: "내 마음 속 잊어버린", romaji: "nae maeum sok ijeobeorin", zh: "在我心中被遺忘的", chant: null },
      { time: 186.0, original: "너를 향한 나의 기억", romaji: "neoreul hyanghan naui gieok", zh: "那屬於你的記憶", chant: null },
      { time: 189.0, original: "Let's go Let's go", romaji: "", zh: "Let's go Let's go", chant: null },
      { time: 192.0, original: "**Move it Move it**", romaji: "", zh: "Move it Move it", chant: "call" },
      { time: 195.0, original: "**Move it**", romaji: "", zh: "Move it", chant: "call" },
      { time: 198.0, original: "너를 찾아서 **Oh A oh**", romaji: "neoreul chajaseo Oh A oh", zh: "為了找尋你", chant: "call" },
      { time: 201.0, original: "날 비춰주는 저 달빛아래로", romaji: "nal bichwojuneun jeo dalbicharaero", zh: "走向那照耀著我的月光之下", chant: null },
      { time: 204.0, original: "저 달빛아래로", romaji: "jeo dalbicharaero", zh: "那月光之下", chant: null },
      { time: 207.0, original: "그댈 찾아서 **Oh A oh oh oh**", romaji: "geudael chajaseo Oh A oh oh oh", zh: "為了找尋親愛的你", chant: "call" },
      { time: 210.0, original: "그대 오 Baby", romaji: "geudae o Baby", zh: "親愛的你 oh Baby", chant: null },
      { time: 213.0, original: "끝이 어딘지 모르겠지만 Hey", romaji: "kkeuchi eodinji moreugetjiman Hey", zh: "雖然不知道盡頭在哪 Hey", chant: null },
      { time: 216.0, original: "어딘지 몰라", romaji: "eodinji molla", zh: "不知道在哪", chant: null },
      { time: 219.0, original: "Tonight Tonight Tonight Tonight", romaji: "", zh: "Tonight Tonight Tonight Tonight", chant: null },
      { time: 222.0, original: "아직 난 사랑을 몰라", romaji: "ajik nan sarangeul molla", zh: "我現在還不懂愛情", chant: null },
      { time: 225.0, original: "사랑을 몰라 난", romaji: "sarangeul molla nan", zh: "我不懂愛情", chant: null },
      { time: 228.0, original: "또 홀로 가여운 이 밤 **사랑해**", romaji: "tto hollo gayeoun i bam saranghae", zh: "又是獨自一人淒涼的夜晚", kongEr: "撒朗嘿", chant: "cheer" },
      { time: 231.0, original: "너를 찾아서 Oh A oh (Tonight)", romaji: "neoreul chajaseo Oh A oh (Tonight)", zh: "為了找尋你 Oh A oh (Tonight)", chant: null },
      { time: 234.0, original: "날 비춰주는 저 달빛아래로 (Such a beautiful night)", romaji: "nal bichwojuneun jeo dalbicharaero (Such a beautiful night)", zh: "走向那照耀著我的月光之下(Such a beautiful night)", chant: null },
      { time: 237.0, original: "그댈 찾아서 Oh A oh oh oh", romaji: "geudael chajaseo Oh A oh oh oh", zh: "為了找尋親愛的你", chant: null },
      { time: 240.0, original: "끝이 어딘지 모르겠지만", romaji: "kkeuchi eodinji moreugetjiman", zh: "雖然不知道盡頭在哪", chant: null },
      { time: 243.0, original: "Goodnight", romaji: "", zh: "Goodnight", chant: null },
    ],
  },
  {
    id: "blue",
    order: 4,
    title: "BLUE",
    titleOriginal: "",
    youtubeId: "zj_tWuMgrPw",
    chantTypes: ["call"],
    categories: ["1st"],
    // 歌詞來源：BIGBANG空耳應援歌詞（N.YDest 空耳／翻譯：大勝鉉愛小志龍），時間點為粗估，待對照影片微調
    lyrics: [
      { time: 3.0, original: "겨울이 가고 봄이 찾아오죠", romaji: "gyeouri gago bomi chajaojyo", zh: "冬季離去 春天會到來的吧", chant: null },
      { time: 6.0, original: "우린 시들고 그리움 속에 맘이 멍들었죠", romaji: "urin sideulgo geurium soge mami meongdeureotjyo", zh: "我們的心在凋零的思念裡傷痕累累", chant: null },
      { time: 9.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 12.0, original: "파란 눈물에 파란 슬픔에 길들여져", romaji: "paran nunmure paran seulpeume gildeuryeojyeo", zh: "在藍色的淚水和藍色的悲傷中被馴服", chant: null },
      { time: 15.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 18.0, original: "뜬구름에 날려보낸 사랑 Oh Oh", romaji: "tteungureume nallyeobonaen sarang Oh Oh", zh: "浮雲中被風吹散的愛情", chant: null },
      { time: 21.0, original: "a-yo 같은 하늘 다른 곳 너와나", romaji: "a-yo gateun haneul dareun got neowana", zh: "a-yo 同一片天空 在不同地方的你和我", chant: null },
      { time: 24.0, original: "위험하니까 너에게서 떠나주는거야", romaji: "wiheomhanikka neoegeseo tteonajuneungeoya", zh: "因為很危險 所以離開了你", chant: null },
      { time: 27.0, original: "님이란 글자에 점 하나", romaji: "nimiran geulja-e jeom hana", zh: "就這樣從戀人成為陌生人", chant: null },
      { time: 30.0, original: "비겁하지만 내가 못나 숨는 거야", romaji: "bigeophajiman naega monna sumneun geoya", zh: "雖然膽小卑鄙 但我只能沒出息的躲藏才能生存", chant: null },
      { time: 33.0, original: "잔인한 이별은 사랑의 **말로**", romaji: "janinhan ibyeoreun sarangui mallo", zh: "殘忍的離別 是愛情的末路", kongEr: "馬摟", chant: "call" },
      { time: 36.0, original: "그어떤 **말도** 위로될 순 없다고 Oh", romaji: "geueotteon maldo wirodoel sun eopdago Oh", zh: "無論說什麼 也無法成為安慰 Oh", kongEr: "mic都", chant: "call" },
      { time: 39.0, original: "아마 내 인생의 마지막 **멜로**", romaji: "ama nae insaengui majimak mello", zh: "大概 我人生的最後劇情", kongEr: "每摟", chant: "call" },
      { time: 42.0, original: "막이 내려오네요 이제", romaji: "magi naeryeooneyo ije", zh: "就要落幕了 現在", chant: null },
      { time: 45.0, original: "태어나서 널 만나고", romaji: "taeeonaseo neol mannago", zh: "來到這世上後與你相遇", chant: null },
      { time: 48.0, original: "죽을만큼 사랑하고", romaji: "jugeulmankeum saranghago", zh: "如死一般的深愛著你", chant: null },
      { time: 51.0, original: "파랗게 물들어 시린 내 맘", romaji: "paratge muldeureo sirin nae mam", zh: "我漸漸冰凍的心 渲染出一片青藍", chant: null },
      { time: 54.0, original: "눈을 감아도 널 느낄 수 없잖아", romaji: "nuneul gamado neol neukkil su eopjana", zh: "即使閉上雙眼也感覺不到你", chant: null },
      { time: 57.0, original: "겨울이 가고 봄이 찾아오죠", romaji: "gyeouri gago bomi chajaojyo", zh: "冬季離去 春天會到來的吧", chant: null },
      { time: 60.0, original: "우린 시들고 그리움 속에 맘이 멍들었죠", romaji: "urin sideulgo geurium soge mami meongdeureotjyo", zh: "我們的心在凋零的思念裡傷痕累累", chant: null },
      { time: 63.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 66.0, original: "파란눈물에 파란 슬픔에 길들여져", romaji: "paranunmure paran seulpeume gildeuryeojyeo", zh: "在藍色的淚水和藍色的悲傷中被馴服", chant: null },
      { time: 69.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 72.0, original: "뜬구름에 날려보낸 사랑 Oh Oh", romaji: "tteungureume nallyeobonaen sarang Oh Oh", zh: "浮雲中被風吹散的愛情", chant: null },
      { time: 75.0, original: "심장이 멎은것만 같아", romaji: "simjangi meojeungeotman gata", zh: "心臟像停擺了一樣", chant: null },
      { time: 78.0, original: "전쟁은 끝났고 그곳에 얼어붙은 **너와나**", romaji: "jeonjaengeun kkeunnatgo geugose eoreobuteun neowana", zh: "戰爭結束後 凍結在那的你和我", kongEr: "no哇那", chant: "call" },
      { time: 81.0, original: "내머리속 새겨진 트라우마", romaji: "naemeorisok saegyeojin teuraouma", zh: "在我腦中深深刻下的創傷", chant: null },
      { time: 84.0, original: "이 눈물 마르면 촉촉히 기억하리 **내사랑**", romaji: "i nunmul mareumyeon chokchoki gieokhari naesarang", zh: "這眼淚乾涸的話 我的愛仍會濕潤的(以淚水來)記得你", kongEr: "內撒朗", chant: "call" },
      { time: 87.0, original: "괴롭지도 외롭지도 않아", romaji: "goeropjido oeropjido ana", zh: "既不痛苦也不孤獨", chant: null },
      { time: 90.0, original: "행복은 다 혼잣말 그이상의 복잡한 건 못참아", romaji: "haengbogeun da honjanmal geuisangui bokjaphan geon motchama", zh: "所謂的幸福 全是自說自話 無法再忍受這複雜的東西了", chant: null },
      { time: 93.0, original: "대수롭지 아무렇지도 않아", romaji: "daesuropji amureochido ana", zh: "那算什麼 沒什麼大不了的", chant: null },
      { time: 96.0, original: "별 수 없는 방황 사람들은 **왔다갔다**", romaji: "byeol su eomneun banghwang saramdeureun watdagatda", zh: "別無他法的徬徨 人們來來去去", kongEr: "哇搭卡搭", chant: "call" },
      { time: 99.0, original: "태어나서 널 만나고", romaji: "taeeonaseo neol mannago", zh: "來到這世上後與你相遇", chant: null },
      { time: 102.0, original: "죽을만큼 사랑하고", romaji: "jugeulmankeum saranghago", zh: "如死一般的深愛著你", chant: null },
      { time: 105.0, original: "파랗게 물들어 시린 내 맘", romaji: "paratge muldeureo sirin nae mam", zh: "我漸漸冰凍的心 渲染出一片青藍", chant: null },
      { time: 108.0, original: "너는 떠나도 난 그대로 있잖아", romaji: "neoneun tteonado nan geudaero itjana", zh: "即使你離開了 我也一如往常不曾改變", chant: null },
      { time: 111.0, original: "겨울이 가고 봄이 찾아오죠", romaji: "gyeouri gago bomi chajaojyo", zh: "冬季離去 春天會到來的吧", chant: null },
      { time: 114.0, original: "우린 시들고 그리움 속에 맘이 멍들었죠", romaji: "urin sideulgo geurium soge mami meongdeureotjyo", zh: "我們的心在凋零的思念裡傷痕累累", chant: null },
      { time: 117.0, original: "오늘도 파란 저 달빛 아래에 나 홀로 잠이 들겠죠", romaji: "oneuldo paran jeo dalbit araee na hollo jami deulgetjyo", zh: "我今天也是在那藍色的月光下 獨自一人入睡吧", chant: null },
      { time: 120.0, original: "꿈속에서도 난 그대를 찾아 헤매이며 이 노래를 불러요", romaji: "kkumsogeseodo nan geudaereul chaja hemaeimyeo i noraereul bulleoyo", zh: "即使在夢中 我仍徘徊著找尋你 一邊唱著這首歌曲", chant: null },
      { time: 123.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 126.0, original: "파란눈물에 파란 슬픔에 길들여져", romaji: "paranunmure paran seulpeume gildeuryeojyeo", zh: "在藍色的淚水和藍色的悲傷中被馴服", chant: null },
      { time: 129.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 132.0, original: "뜬구름에 날려보낸 사랑", romaji: "tteungureume nallyeobonaen sarang", zh: "浮雲中被風吹散的愛情", chant: null },
      { time: 135.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 138.0, original: "파란눈물에 파란 슬픔에 길들여져", romaji: "paranunmure paran seulpeume gildeuryeojyeo", zh: "在藍色的淚水和藍色的悲傷中被馴服", chant: null },
      { time: 141.0, original: "I'm singing my **blues**", romaji: "I'm singing my blues", zh: "I'm singing my blues", chant: "call" },
      { time: 144.0, original: "뜬구름에 날려보낸 사랑 **Oh Oh**", romaji: "tteungureume nallyeobonaen sarang Oh Oh", zh: "浮雲中被風吹散的愛情", chant: "call" },
    ],
  },
];
